### ISSUE TITLE
Protobuf configuration is outdated

### ISSUE THREAD

**Issue by silvanfischer** [orrc/android-bundle-basics-lib#1] opened 2020-07-13 10:44 UTC
It seems that the protobuf configuration is outdated. It can't read the anything else then the package name from the bundle. Is there any plan to update it? That would be super nice :)

**Comment by orrc** [comment] 2020-07-13 17:39
If we have a way of reproducing the issue, I can take a look sometime.

There don't appear to have been any changes in the AOSP repo to the [proto file](https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-10.0.0_r3/tools/aapt2/Resources.proto) that this tool uses. Can you elaborate a little on how you determined that the protobuf is outdated?

I'd be surprised if the bundle format has been changed in some backward-incompatible way. I see that bundletool has had a lot of releases over time, but the [`DumpManager` class](https://github.com/google/bundletool/compare/0.10.3...1.0.0#diff-2ecd27258d9a2f7fe9aea10c6d887874) that this tool uses appears relatively unchanged.

Can you share how to reproduce the creation of a bundle that can't be parsed by this tool?
What error or output do you see?

**Comment by silvanfischer** [comment] 2020-07-14 06:03
The thing is, with your tool I always get an empty string back but when I use `bundletool dump manifest --bundle myApp.aab --xpath /manifest/@android:versionCode` it works as expected.
We generate the bundle with the gradle command `bundle[Flavor]Release`. We also use Dexguard for obfuscation but I don't think this has an impact.

I also tried to copy the new files from bundletool (`DumpManager`, etc) and use it in this lib, but I still get an empty string :(.

**Comment by silvanfischer** [comment] 2020-07-14 07:00
Okay, I just verified that it's due to Dexguard. But still, it's weird that it works with `bundletool dump manifest --bundle myApp.aab --xpath /manifest/@android:versionCode`. It seems that it takes the mappings into account.

with dexguard:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" _0x0101021c_="16.5.0.86766a0184" _0x01010572_="29" _0x01010573_="10" android:installLocation="0" android:versionCode="160500001" package="x.y.z" platformBuildVersionCode="29" platformBuildVersionName="10">

    <uses-sdk _0x0101020c_="23" _0x01010270_="29"/>

    <uses-permission _0x01010003_="android.permission.INTERNET"/>
    <uses-permission _0x01010003_="android.permission.ACCESS_NETWORK_STATE"/>
....
```

without dexguard:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:compileSdkVersion="29" android:compileSdkVersionCodename="10" android:installLocation="0" android:versionCode="160500001" android:versionName="16.5.0.86766a0184" package="x.y.z" platformBuildVersionCode="29" platformBuildVersionName="10">

    <uses-sdk android:minSdkVersion="23" android:targetSdkVersion="29"/>

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
....
```


One solution would be to use the bundletool as a direct dependency in the GooglePlayAndroidPublisher instead of this lib.

**Comment by orrc** [comment] 2020-07-14 09:12
> Okay, I just verified that it's due to Dexguard. But still, it's weird that it works with `bundletool dump manifest --bundle myApp.aab --xpath /manifest/@android:versionCode`. It seems that it takes the mappings into account.

Oh, that's interesting. Thanks for the info!

I'm not sure why DexGuard goes out of its way to obfuscate obvious XML attributes that Android and Google Play need to be able to understand, but `0x0101020c` is the Android resource ID for `android:minSdkVersion` (and bundletool [knows](https://github.com/google/bundletool/blob/1.0.0/src/main/java/com/android/tools/build/bundletool/model/AndroidManifest.java#L106) this).

So I guess fixing this should at least be somewhat straightforward. I'll have to look into more detail about how the dump command deals with this.

> One solution would be to use the bundletool as a direct dependency in the GooglePlayAndroidPublisher instead of this lib.

We didn't really want to depend on an external tool being installed on the build agent, but as you say, it's technically possible to pull in bundletool as a library.  Or bundling the CLI tool could have been an alternative.

Joe did some work on the integration, and tried to split out the parsing code since bundletool is such a [huge dependency](https://github.com/google/bundletool/issues/103) (not that it massively matters for a Jenkins plugin).

When I took over work on AAB support, integrating bundletool directly is something I tried to get working for a long time, however its dependency on Guava causes _really_ horrible classpath issues with Jenkins — which is a longstanding Jenkins problem.  If I could have gotten away with not creating my own library, just to avoid nasty compatibility issues, I definitely would have :)

But I'll try and see if I can figure out the parsing code, maybe sometime at the end of the week.

I also opened [JENKINS-63063](https://issues.jenkins-ci.org/browse/JENKINS-63063) to keep track from the plugin side.

**Comment by silvanfischer** [comment] 2020-07-14 09:25
nice! Thanks a lot! I'm trying a bit with that integration of `bundletool` as a lib into the GooglePlayAndroidPublisher. I'll keep you posted

**Comment by silvanfischer** [comment] 2020-08-31 07:13
@orrc did you have any chance to look into this issue?

**Comment by orrc** [comment] 2020-08-31 21:43
Only briefly, but all I've managed to create so far is a bundle file that crashes `bundletool`… 😅

Would you be able to share a minimal `.aab` file that has the above problem, or give steps to create one (though I guess that might require having DexGuard)?

**Comment by orrc** [comment] 2020-09-26 15:19
Alrighty, this should be fixed now. Thanks for the sample file!

```
$ ./gradlew shadowJar
…

$ java -jar build/libs/bundle-basics-all.jar test.aab

Application ID:   com.example.bundle
Version code:     170300061
minSdkVersion:    23
targetSdkVersion: 30
```

I've tagged this repo with `v3`, and will update the Jenkins plugin via [JENKINS-63063](https://issues.jenkins-ci.org/browse/JENKINS-63063).

**Closed as completed by orrc** 2020-09-26 15:19 UTC
